server.port: 9000
eureka.instance.hostname: 192.168.18.12
eureka.client.register-with-eureka: false
eureka.client.fetch-registry: false
eureka.client.registerWithEureka: false
eureka.client.fetchRegistry: false
eureka.client.serviceUrl.defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/